# Generated by Django 4.2.5 on 2023-09-05 05:09

import bookmarks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=bookmarks.models.TruncatingCharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=bookmarks.models.TruncatingCharField(max_length=256, unique=True),
        ),
    ]
